lookup = {
"Ab":["Abraham"],
"Abig":["Abigail"],
"Abr":["Abraham"],
"Abra":["Abraham"],
"Ad":["	Adelard"],
"Adr":["Adrian","Adrien","Adrienne"],
"Agn":["Agnes"],
"Alb":["Albert","Albina"],
"Albt":["Albert"],
"Alc":["Alice"],
"Alex":["Alexander","Alexandre","Alexandrine"],
"Ale":["Alethea"],
"Alf":["Alfred"],
"Alfd":["Alfred"],
"Alph":["Alphonse","Alphonsine"],
"Am":["Amanda"],
"Amb":["Ambrose"],
"And":["Andrew","André"],
"Andw":["Andrew"],
"Ang":["Angeline","Angelique"],
"An":["Anne","Anna"],
"Ani":["Annie"],
"Ant":["Antoine","Antoinette"],
"Anth":["Anthony"],
"Anthy":["Anthony"],
"Arch":["Archibald"],
"Archd":["Archibald"],
"Art":["Arthur"],
"Arth":["Arthur","Arthemise"],
"Aud":["Audrey"],
"Aug":["August","Auguste","Augustin","Augustine"],
"Balt":["Balthazar"],
"Barb":["Barbara"],
"Bart":["Bartholomew"],
"Barth":["Barthelemy"],
"Bea":["Beatrice"],
"Ben":["Benjamin"],
"Benj":["Benjamin"],
"Bern":["Bernard","Bernadette"],
"Brid":["Bridget","Bridgette"],
"Car":["Caroline"],
"Cath":["Catherine"],
"Cathne":["Catherine"],
"Charlt":["Charlotte"],
"Chals":["Charles"],
"Chas":["Charles"],
"Chs":["Charles"],
"Chris":["Christopher"],
"Clem":["Clement","Clementine"],
"Clif":["Clifford"],
"Clifd":["Clifford"],
"Cons":["Constance"],
"Const":["Constance"],
"Corn":["Cornelius"],
"Cor’us":["Cornelius"],
"Cuthbt":["Cuthbert"],
"Dan":["Daniel"],
"Danl":["Daniel"],
"Dav":["David"],
"Deb":["Deborah"],
"Delbt":["Delbert"],
"Den":["Dennis"],
"Dom":["Dominique"],
"Don":["Donald"],
"Dor":["Dorothy"],
"Doug":["Douglas"],
"Dy":["Dorothy"],
"Eben":["Ebenezer"],
"Ed":["Edward","Edouard","Edmund"],
"Edm":["Edmond","Edmund"],
"Edw":["Edward"],
"Elis":["Elisabeth"],
"Eliz":["Elizabeth"],
"Eliza":["Elizabeth"],
"Elizh":["Elizabeth"],
"Elizth":["Elizabeth"],
"Elnr":["Eleanor"],
"Em":["Emmanuel","Emma","Emily"],
"Eml":["Emily"],
"Ern":["Ernest","Ernestine"],
"Esth":["Esther"],
"Etne":["Etienne"],
"Euc":["Euclide"],
"Eug":["Eugene","Eugenie"],
"Eugne":["Eugene"],
"Eus":["Eustace"],
"Ezek":["Ezekiel"],
"Fel":["Felicite"],
"Ferd":["Ferdinand"],
"Fern":["Fernand","Fernande"],
"Flo":["Florence"],
"Flor":["Florence"],
"Fra":["Francis (male)"],
"Fran":["Frances (female)"],
"Fred":["Frederick","Frédéric"],
"Fredk":["Frederick"],
"Fs":["Francis (male)"],
"Frs":["Francis (male)","Frances (female)","François","Françoise"],
"Frs. X":["François-Xavier"],
"Gab":["Gabrielle"],
"Gen":["Genevieve"],
"Geo":["George","Georges","Georgette","Georgina","Georgiana"],
"Geof":["Geoffrey"],
"Ger":["Gerald","Geraldine","Gerard"],
"Germ":["Germaine"],
"Gert":["Gertrude"],
"Gilbt":["Gilbert"],
"Godf":["Godfrey"],
"Graz":["Graziella"],
"Grif":["Griffith"],
"Gul":["William (in Latin Gulielmus)"],
"Guliel":["William (in Latin Gulielmus)"],
"Gwen":["Gwendolyn"],
"Han":["Hannah"],
"Har":["Harold"],
"Hel":["Helen","Hellene"],
"Hen":["Henry"],
"Henr":["Henriette"],
"Hep":["Hephzibah"],
"Herb":["Herbert"],
"Herbt":["Herbert"],
"Hest":["Hester"],
"Hon":["Honour"],
"Hub":["Hubert"],
"Hubt":["Hubert"],
"Hum":["Humphrey"],
"Humy":["Humphrey"],
"Hy":["Henry"],
"Ioh":["John (in Latin)"],
"Ir":["Irene"],
"Isab":["Isabel","Isabelle"],
"Isb":["Isabel","Isabelle"],
"Ja":["James"],
"Jabus":["James (in Latin Jacobus)"],
"Jac":["James (in Latin Jacobus)"],
"Jacq":["Jacques","Jacquelline"],
"J. Bte":["Jean-Baptiste"],
"Jas":["James"],
"Jean":["Jean","Jeannette"],
"Jer":["Jeremiah"],
"Jere":["Jeremiah"],
"Jerh":["Jeremiah"],
"Jermh":["Jeremiah"],
"Jn":["John","Jean"],
"Jne":["Jeanne"],
"Jno":["John"],
"Jnthn":["Jonathan"],
"Jon":["Jonathan"],
"Jone":["Joan (sometimes misspelt)"],
"Jos":["Joseph","Joséphat"],
"Josh":["Joshua","Josiah"],
"Jro":["Jerome"],
"Jsph":["Joseph"],
"Jud":["Judith"],
"Jul":["Julian","Juliette"],
"Kath":["Katherine"],
"Ken":["Kenneth"],
"Lan":["Lancelot"],
"Lau":["Laurence"],
"Lawr":["Lawrence"],
"Len":["Leonard"],
"Leo":["Leopold"],
"Leon":["Leonard"],
"Let":["Letitia","Lettice"],
"Ls":["Louis"],
"Lse":["Louise"],
"Luc":["Lucian","Lucien","Lucienne"],
"Lyd":["Lydia"],
"Mad":["Madeleine"],
"Marc":["Marcelline"],
"Marg":["Margaret","Marguerite"],
"Margt":["Margaret"],
"Mart":["Martha"],
"Margt":["Margaret"],
"Margy":["Margery"],
"Marm":["Marmaduke"],
"Mat":["Matthias","Mathias","Matthew","Mathieu"],
"Math":["Mathias","Mathilde"],
"Mathw":["Mathew"],
"Matt":["Mathew"],
"Mau":["Maurice"],
"Mgt":["Margaret"],
"Mic":["Michael"],
"Mich":["Michael","Miche"],
"Michl":["Michael"],
"Mill":["Millicent"],
"My":["Mary"],
"Nap":["Napoleon"],
"Nar":["Narcisse"],
"Nath":["Nathaniel"],
"Nathl":["Nathaniel"],
"Naz":["Nazaire"],
"Neh":["Nehemiah"],
"Nic":["Nicholas","Nicole"],
"Nich":["Nicholas"],
"Nicho":["Nicholas"],
"Nichs":["Nicholas"],
"Ns":["Nicholas"],
"Oct":["Octave"],
"Ol":["Oliver","Olivier"],
"Pama":["Pamelia"],
"Pat":["Patrick","Patrice","Patricia"],
"Patk":["Patrick"],
"Pen":["Penelope"],
"Pet":["Peter"],
"Ph":["Phillip","Philippe"],
"Phil":["Phillip","Philippe"],
"Phin":["Phineas"],
"Phyl":["Phyllis"],
"Pre":["Pierre"],
"Prisc":["Priscilla"],
"Pru":["Prudence"],
"Rach":["Rachel"],
"Ray":["Raymond"],
"Rayd":["Raymond"],
"Reb":["Rebecca"],
"Reba":["Rebecca"],
"Reg":["Reginald"],
"Regd":["Reginald"],
"Ric":["Richard"],
"Rich":["Richard"],
"Richd":["Richard"],
"Richdus":["Richardus (Richard in Latin)"],
"Robt":["Robert"],
"Rodk":["Roderick"],
"Rog":["Roger"],
"Rol":["Roland"],
"Ron":["Ronald"],
"Rowl":["Rowland"],
"Rph":["Ralph"],
"Sam":["Samuel"],
"Saml":["Samuel"],
"Sar":["Sarah"],
"Sid":["Sidney"],
"Silv":["Sylvester"],
"Sim":["Simon"],
"Sol":["Solomon"],
"Stan":["Stanley"],
"Steph":["Stephen"],
"Sus":["Susan","Susanna"],
"Susna":["Susanna","Susannah"],
"Suz":["Suzanne"],
"Syd":["Sydney"],
"Tam":["Thomasin","Tamsin"],
"Teles":["Telesphore"],
"Theo":["Theodore"],
"Ther":["Therese"],
"Tho":["Thomas"],
"Thos":["Thomas"],
"Ths":["Thomas"],
"Tim":["Timothy"],
"Tous":["Toussaint"],
"Tristm":["Tristram"],
"Urs":["Ursala"],
"Val":["Valentine"],
"Vic":["Victor"],
"Vinc":["Vincent"],
"Virg":["Virginia"],
"Walt":["Walther"],
"Wilf":["Wilfred","Wilfrid"],
"Wilfd":["Wilfred"],
"Wm":["William"],
"Xpher":["Christopher (in Latin)"],
"Xpr":["Christopher (in Latin)"],
"Xtianus":["Christian (in Latin)"],
"Xtopherus":["Christopher (in Latin)"],
"Zach":["Zachariah"],
}

def get(x):
    if x in lookup:
        return lookup[x][0]
    return x

def find(x):
    if x in lookup:
        return lookup[x][0]
    return None
